files:
  - source: /resources/languages/flat/en_us.json
    translation: /resources/languages/flat/%locale_with_underscore%.json
  - source: /resources/readme/en_us.md
    translation: /resources/readme/%locale_with_underscore%.md
