version: '3.5'
services:
  mc-linker:
    image: lianecx/mc-linker
    container_name: mc-linker
    restart: on-failure
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    volumes:
      - type: bind
        source: ./serverdata
        target: /usr/src/app/serverdata
      - type: bind
        source: ./userdata
        target: /usr/src/app/userdata
