version: '3.5'
services:
  mc-linker:
    image: lianecx/${SERVICE_NAME}
    container_name: ${SERVICE_NAME}
    restart: on-failure
    ports:
      - "${BOT_PORT}:${BOT_PORT}"
    volumes:
      - type: bind
        source: ./download-cache
        target: /usr/src/app/download-cache
  mongodb:
    image: mongo
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - type: bind
        source: ./mongodb
        target: /data/db
